<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-L8D6NFS" failures="1" tests="1" name="Test3" time="14.922" errors="0" timestamp="2023-08-30T15:53:12 IST">
  <testcase classname="TestNg1.MultitestRun" name="TestOrangeHRM" time="10.07">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at TestNg1.MultitestRun.TestOrangeHRM(MultitestRun.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TestOrangeHRM -->
  <testcase classname="TestNg1.MultitestRun" name="TestFacebook" time="0.0">
    <ignored/>
  </testcase> <!-- TestFacebook -->
  <testcase classname="TestNg1.MultitestRun" name="testgoogle" time="0.0">
    <ignored/>
  </testcase> <!-- testgoogle -->
</testsuite> <!-- Test3 -->
